version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data # <-- Слева имя тома, справа путь в контейнере

volumes:
  pg: # <-- обязательно двоеточие. Даже если нет настроек, двоеточие нужно!
