version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - pg_/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo -d todoapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://todo:secret@db:5432/todoapp?sslmode=disable",
        "up",
      ]
    restart: "no"

  app:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      PORT: 8080
      JWT_SECRET: supersecretkey123
      DATABASE_URL: postgres://todo:secret@db:5432/todoapp?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  pg_:
